import Head from "next/head";
import React, { ReactNode, FC } from "react";
import Footer from "./Footer";
import NavBar from "./NavBar";

interface LayoutProps {
  children?: ReactNode;
}

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Photo-House</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="title"
        />
        <link rel="icon" href="/icon.png" />
      </Head>
      <NavBar />
      <main className="min-h-[100vh]">{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
